version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: trello-lite-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanager
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trello-lite-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/taskmanager?schema=public"
      JWT_ACCESS_SECRET: "your-super-secret-access-key"
      JWT_REFRESH_SECRET: "your-super-secret-refresh-key"
      SUPABASE_URL: "YOUR_SUPABASE_URL"
      SUPABASE_SERVICE_KEY: "YOUR_SUPABASE_SERVICE_KEY"

volumes:
  postgres_data:
